#!/usr/bin/env python3
"""
Enterprise Tools Setup Wizard
Interactive configuration for Jira, Confluence, Slack, GitLab
"""

import argparse
import os
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    print("Installing required package: requests")
    os.system(f"{sys.executable} -m pip install requests")
    import requests


CONFIG_DIR = Path.home() / '.enterprise-tools'
CREDENTIALS_FILE = CONFIG_DIR / 'credentials.env'


def create_config_dir():
    """Create config directory if not exists"""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def read_existing_config():
    """Read existing configuration"""
    config = {}
    if CREDENTIALS_FILE.exists():
        with open(CREDENTIALS_FILE) as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    config[key] = value.strip('"\'')
    return config


def write_config(config):
    """Write configuration to file"""
    create_config_dir()

    lines = [
        "# Enterprise Tools Configuration",
        "# Generated by setup-wizard.py",
        "",
        "# Jira (Atlassian Cloud)",
        f'JIRA_BASE_URL="{config.get("JIRA_BASE_URL", "")}"',
        f'JIRA_EMAIL="{config.get("JIRA_EMAIL", "")}"',
        f'JIRA_API_TOKEN="{config.get("JIRA_API_TOKEN", "")}"',
        "",
        "# Confluence (Atlassian Cloud)",
        f'CONFLUENCE_BASE_URL="{config.get("CONFLUENCE_BASE_URL", "")}"',
        f'CONFLUENCE_EMAIL="{config.get("CONFLUENCE_EMAIL", "")}"',
        f'CONFLUENCE_API_TOKEN="{config.get("CONFLUENCE_API_TOKEN", "")}"',
        "",
        "# Slack",
        f'SLACK_BOT_TOKEN="{config.get("SLACK_BOT_TOKEN", "")}"',
        "",
        "# GitLab",
        f'GITLAB_BASE_URL="{config.get("GITLAB_BASE_URL", "https://gitlab.com")}"',
        f'GITLAB_TOKEN="{config.get("GITLAB_TOKEN", "")}"',
        ""
    ]

    with open(CREDENTIALS_FILE, 'w') as f:
        f.write('\n'.join(lines))

    # Set restrictive permissions
    os.chmod(CREDENTIALS_FILE, 0o600)

    print(f"\n✅ Configuration saved to: {CREDENTIALS_FILE}")


def test_jira(base_url, email, token):
    """Test Jira connection"""
    try:
        url = f"{base_url.rstrip('/')}/rest/api/3/myself"
        response = requests.get(url, auth=(email, token), timeout=10)
        if response.status_code == 200:
            user = response.json()
            print(f"  ✅ Jira: Connected as {user.get('displayName', 'Unknown')}")
            return True
        else:
            print(f"  ❌ Jira: HTTP {response.status_code}")
            return False
    except Exception as e:
        print(f"  ❌ Jira: {e}")
        return False


def test_confluence(base_url, email, token):
    """Test Confluence connection"""
    try:
        url = f"{base_url.rstrip('/')}/wiki/rest/api/user/current"
        response = requests.get(url, auth=(email, token), timeout=10)
        if response.status_code == 200:
            user = response.json()
            print(f"  ✅ Confluence: Connected as {user.get('displayName', 'Unknown')}")
            return True
        else:
            print(f"  ❌ Confluence: HTTP {response.status_code}")
            return False
    except Exception as e:
        print(f"  ❌ Confluence: {e}")
        return False


def test_slack(token):
    """Test Slack connection"""
    try:
        url = "https://slack.com/api/auth.test"
        headers = {'Authorization': f'Bearer {token}'}
        response = requests.get(url, headers=headers, timeout=10)
        data = response.json()
        if data.get('ok'):
            print(f"  ✅ Slack: Connected as @{data.get('user', 'Unknown')} in {data.get('team', 'Unknown')}")
            return True
        else:
            print(f"  ❌ Slack: {data.get('error', 'Unknown error')}")
            return False
    except Exception as e:
        print(f"  ❌ Slack: {e}")
        return False


def test_gitlab(base_url, token):
    """Test GitLab connection"""
    try:
        url = f"{base_url.rstrip('/')}/api/v4/user"
        headers = {'PRIVATE-TOKEN': token}
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            user = response.json()
            print(f"  ✅ GitLab: Connected as @{user.get('username', 'Unknown')}")
            return True
        else:
            print(f"  ❌ GitLab: HTTP {response.status_code}")
            return False
    except Exception as e:
        print(f"  ❌ GitLab: {e}")
        return False


def setup_jira(config):
    """Setup Jira configuration"""
    print("\n=== Jira Configuration ===")
    print("Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens")
    print()

    base_url = input(f"Jira URL [{config.get('JIRA_BASE_URL', 'https://your-company.atlassian.net')}]: ").strip()
    if not base_url:
        base_url = config.get('JIRA_BASE_URL', '')

    email = input(f"Email [{config.get('JIRA_EMAIL', '')}]: ").strip()
    if not email:
        email = config.get('JIRA_EMAIL', '')

    token = input("API Token (hidden): ").strip()
    if not token:
        token = config.get('JIRA_API_TOKEN', '')

    if base_url and email and token:
        config['JIRA_BASE_URL'] = base_url
        config['JIRA_EMAIL'] = email
        config['JIRA_API_TOKEN'] = token

    return config


def setup_confluence(config):
    """Setup Confluence configuration"""
    print("\n=== Confluence Configuration ===")
    print("Uses same credentials as Jira for Atlassian Cloud")
    print()

    # Default to Jira values if available
    default_url = config.get('JIRA_BASE_URL', 'https://your-company.atlassian.net')
    default_email = config.get('JIRA_EMAIL', config.get('CONFLUENCE_EMAIL', ''))
    default_token = config.get('JIRA_API_TOKEN', config.get('CONFLUENCE_API_TOKEN', ''))

    base_url = input(f"Confluence URL [{config.get('CONFLUENCE_BASE_URL', default_url)}]: ").strip()
    if not base_url:
        base_url = config.get('CONFLUENCE_BASE_URL', default_url)

    email = input(f"Email [{default_email}]: ").strip()
    if not email:
        email = default_email

    use_same = input("Use same API token as Jira? [Y/n]: ").strip().lower()
    if use_same != 'n':
        token = default_token
    else:
        token = input("API Token: ").strip()
        if not token:
            token = config.get('CONFLUENCE_API_TOKEN', '')

    if base_url and email and token:
        config['CONFLUENCE_BASE_URL'] = base_url
        config['CONFLUENCE_EMAIL'] = email
        config['CONFLUENCE_API_TOKEN'] = token

    return config


def setup_slack(config):
    """Setup Slack configuration"""
    print("\n=== Slack Configuration ===")
    print("Create a Slack app at: https://api.slack.com/apps")
    print("Required scopes: chat:write, channels:read, users:read, search:read")
    print()

    token = input(f"Bot Token (xoxb-...) [{config.get('SLACK_BOT_TOKEN', '')[:20]}...]: ").strip()
    if not token:
        token = config.get('SLACK_BOT_TOKEN', '')

    if token:
        config['SLACK_BOT_TOKEN'] = token

    return config


def setup_gitlab(config):
    """Setup GitLab configuration"""
    print("\n=== GitLab Configuration ===")
    print("Create a personal access token at: https://gitlab.com/-/profile/personal_access_tokens")
    print("Required scopes: api, read_api, read_repository")
    print()

    base_url = input(f"GitLab URL [{config.get('GITLAB_BASE_URL', 'https://gitlab.com')}]: ").strip()
    if not base_url:
        base_url = config.get('GITLAB_BASE_URL', 'https://gitlab.com')

    token = input(f"Personal Access Token [{config.get('GITLAB_TOKEN', '')[:10]}...]: ").strip()
    if not token:
        token = config.get('GITLAB_TOKEN', '')

    if base_url and token:
        config['GITLAB_BASE_URL'] = base_url
        config['GITLAB_TOKEN'] = token

    return config


def run_tests(config):
    """Test all configured services"""
    print("\n=== Testing Connections ===")

    if config.get('JIRA_BASE_URL') and config.get('JIRA_EMAIL') and config.get('JIRA_API_TOKEN'):
        test_jira(config['JIRA_BASE_URL'], config['JIRA_EMAIL'], config['JIRA_API_TOKEN'])

    if config.get('CONFLUENCE_BASE_URL') and config.get('CONFLUENCE_EMAIL') and config.get('CONFLUENCE_API_TOKEN'):
        test_confluence(config['CONFLUENCE_BASE_URL'], config['CONFLUENCE_EMAIL'], config['CONFLUENCE_API_TOKEN'])

    if config.get('SLACK_BOT_TOKEN'):
        test_slack(config['SLACK_BOT_TOKEN'])

    if config.get('GITLAB_TOKEN'):
        test_gitlab(config.get('GITLAB_BASE_URL', 'https://gitlab.com'), config['GITLAB_TOKEN'])


def interactive_setup():
    """Run interactive setup wizard"""
    print("=" * 50)
    print("  Enterprise Tools Setup Wizard")
    print("=" * 50)

    config = read_existing_config()

    services = {
        '1': ('Jira', setup_jira),
        '2': ('Confluence', setup_confluence),
        '3': ('Slack', setup_slack),
        '4': ('GitLab', setup_gitlab),
        '5': ('All services', None),
    }

    print("\nWhich service do you want to configure?")
    for key, (name, _) in services.items():
        print(f"  {key}. {name}")
    print("  0. Test existing configuration")
    print()

    choice = input("Enter choice [5]: ").strip() or '5'

    if choice == '0':
        run_tests(config)
        return

    if choice == '5':
        config = setup_jira(config)
        config = setup_confluence(config)
        config = setup_slack(config)
        config = setup_gitlab(config)
    elif choice in services:
        _, setup_func = services[choice]
        if setup_func:
            config = setup_func(config)

    write_config(config)
    run_tests(config)


def main():
    parser = argparse.ArgumentParser(description='Enterprise Tools Setup Wizard')
    parser.add_argument('--service', choices=['jira', 'confluence', 'slack', 'gitlab', 'all'],
                       help='Configure specific service')
    parser.add_argument('--test', action='store_true', help='Test existing configuration')
    parser.add_argument('--show', action='store_true', help='Show current configuration')

    args = parser.parse_args()

    if args.show:
        config = read_existing_config()
        print("\nCurrent Configuration:")
        print("-" * 40)
        for key, value in config.items():
            # Mask sensitive values
            if 'TOKEN' in key or 'PASSWORD' in key:
                display = value[:10] + '...' if value else '(not set)'
            else:
                display = value or '(not set)'
            print(f"  {key}: {display}")
        return

    if args.test:
        config = read_existing_config()
        run_tests(config)
        return

    if args.service:
        config = read_existing_config()
        if args.service == 'jira':
            config = setup_jira(config)
        elif args.service == 'confluence':
            config = setup_confluence(config)
        elif args.service == 'slack':
            config = setup_slack(config)
        elif args.service == 'gitlab':
            config = setup_gitlab(config)
        elif args.service == 'all':
            config = setup_jira(config)
            config = setup_confluence(config)
            config = setup_slack(config)
            config = setup_gitlab(config)

        write_config(config)
        run_tests(config)
    else:
        interactive_setup()


if __name__ == '__main__':
    main()
